plugins { id 'com.android.application' }
android {
    namespace 'com.pollyjr.treegame'
    compileSdk 34
    defaultConfig {
        applicationId "com.pollyjr.treegame"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "0.2-debug"
    }
    buildTypes {
        debug {
            debuggable true
            applicationIdSuffix ".debug"
            versionNameSuffix "-DEBUG"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
